failure logs as separate step

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -42,12 +42,13 @@ jobs:
       - name: Run server
         run: |
           docker compose up -d
-          echo "=== Docker Compose Logs ==="
-          docker compose logs
-          echo "=== Prestart Container Logs ==="
-          docker compose logs prestart
-          echo "=== Backend Container Logs ==="
-          docker compose logs backend
+
+      - name: Fallback logic
+        if: failure()
+        run: |
+          echo "Benchmark failed. Running fallback logic.."
+          docker compose logs -f prestart
+          exit 1
 
       - name: Wait for server to be ready
         run: sleep 10
